### ISSUE TITLE
Issues with number of calls to the Habitica API

### ISSUE THREAD

**Issue by paglias** [delightedCrow/MMM-HabiticaStats#1]
Hi @delightedCrow , Matteo from Habitica here.

We've had some issues with an user of this module unknowingly making hundreds of thousands of requests to the content API  in a very short period of time.

We're still unsure if this was caused by setting a zero `refreshRate` or if there's some loop in the code but I've noticed a few things:

- here https://github.com/delightedCrow/MMM-HabiticaStats/blob/master/MMM-HabiticaStats.js#L74-L85 the catch block is entered only if there's an error when calling `JSON.parse(fetchError)`
- in the HabiticaMagic code here https://github.com/delightedCrow/HabiticaMagic/blob/master/src/HabiticaAPIManager.js#L130 you're resolving the Promise without an error only if the code is `200` but for example the content api often returns a 304 code if the browser (in this case the Electron app) has already cached the last version of the file and nothing has changed. It would be considered as an error even though it's not. I would suggest to use an external library that's been built specifically for making AJAX requests as it's not easy to make it right (for example jQuery.ajax, axios) or the Fetch API which is now available in every browser https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
- But I think the biggest issue is in this code https://github.com/delightedCrow/MMM-HabiticaStats/blob/master/MMM-HabiticaStats.js#L92 , in particular every time you call `scheduleUpdate` from here https://github.com/delightedCrow/MMM-HabiticaStats/blob/master/MMM-HabiticaStats.js#L68 a new interval is created because the previous one is never cleared. So for example after 10 times that `scheduleUpdate` has been called you'll have 10 timers that will call the Habitica API at the refresh rate and every time one of them returns correctly a new timer is created increasing exponentially the number of intervals

please let me know if you can fix these issues and if you have any question :)

Ah, I'd also make sure the refresh rate cannot be set lower than 30s to avoid API calls being made too often as explained here https://habitica.fandom.com/wiki/Guidance_for_Comrades

**Comment by delightedCrow** [comment]
hi, thanks for reaching out and creating a ticket with all this info! I'll take a look and hopefully get this fixed soon 👍

**Comment by delightedCrow** [comment]
I've verified that the issue was in the `scheduleUpdate` function; we meant to be using setTimeout but were using setInterval instead, which was causing an exponential number of timers as you suspected (sorry about that!). It has been fixed now in the v1.3.0 update. I've also added a check on the config setting to ensure that the refresh rate can't be set lower than every 30 seconds. 

I've updated our x-client ID in API requests to include the module's release version number, so if any future issues arise it will be obvious which version of MMM-HabiticaStats is making any problematic calls to the API. 

Thanks again for the bug report, please let us know if any other issues arise :)

**Comment by paglias** [comment]
@delightedCrow thanks for fixing this quickly! Using setTimeout will definitely fix the issue with the big number of requests but I think you might want to also change the Ajax request in HabiticaMagic to be able to consider status codes like 304 as success  for the content api calls

**Comment by delightedCrow** [comment]
@paglias would you mind adding your issue to the [HabiticaMagicJS](https://github.com/delightedCrow/HabiticaMagic) repo directly? It's a more appropriate place for discussion and issues that pertain directly to HabiticaMagicJS. Thanks!
