### ISSUE TITLE
Could not connect to Habitica server

### ISSUE THREAD

**Issue by icco** [delightedCrow/MMM-HabiticaStats#2]
I get the error `Could not connect to Habitica server..` when I load it.

```js
    {
      module: "MMM-HabiticaStats",
      position: "bottom_right",
      config: {
        userID: "a22efff0-2af3-4bce-8075-e810ea228871",
        APIToken: "truncated"
      }
    },
```

**Comment by delightedCrow** [comment]
Thanks for the report. Are you getting any other errors in the dev console?

**Comment by icco** [comment]
So I'm using a raspberry pi without a keyboard or mouse. Not sure how to see console.

**Comment by icco** [comment]
Ah figured out how to get it:

```
07:14:29.731 magicmirroros.local/:1 Access to XMLHttpRequest at 'https://habitica.com/api/v3/content?language=en' from origin 'http://magicmirroros.local:8080' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://oldgods.net' that is not equal to the supplied origin.
```

**Comment by icco** [comment]
What's interesting is it seems to be intermittent.

**Comment by delightedCrow** [comment]
Ahhh yeah, the dreaded CORS bug. This seems to be an intermittent issue with Habitica’s servers - it seems every once in a while they just stop serving the content API requests to domains that aren’t oldgods.net. I left a bug report on their GitHub issue for it a while back, but not sure there’s anything else I can do about this one.

**Comment by icco** [comment]
Ah, looks like it's https://github.com/HabitRPG/habitica/issues/12383. Yup nothing we can do, closing. Thanks!
